### ISSUE TITLE
CodeCov Not Picking Up Futures Coverage

### ISSUE THREAD

**Issue by eshrubs** [spotify/java-hamcrest#6]
I am unsure why but codecov is currently reporting 50% coverage, due to missed coverage in the Futures package. I am having troubles with this locally as well, but I notice that when running them in IntelliJ they are 80%+ on every class.

**Comment by mattnworb** [comment]
The output from the codecov command on travis has:

```
==> Reading reports
    + ./future/target/site/jacoco/jacoco.xml bytes=31094
    + ./jackson/target/site/jacoco/jacoco.xml bytes=30680
    + ./optional/target/site/jacoco/jacoco.xml bytes=7063
    + ./pojo/target/site/jacoco/jacoco.xml bytes=8231
    + ./util/target/site/jacoco/jacoco.xml bytes=4264
```

so it is generating a report, but seems like nothing is being reported.

If I run the tests locally with `mvn clean test`, my `future/target/site/jacoco/jacoco.xml` has `covered="0"` for everything, for example the bottom of the file looks like:

```xml
      <counter type="BRANCH" missed="2" covered="0"/>
      <counter type="LINE" missed="21" covered="0"/>
      <counter type="COMPLEXITY" missed="4" covered="0"/>
      <counter type="METHOD" missed="3" covered="0"/>
      <counter type="CLASS" missed="1" covered="0"/>
    </sourcefile>
    <counter type="INSTRUCTION" missed="618" covered="0"/>
    <counter type="BRANCH" missed="34" covered="0"/>
    <counter type="LINE" missed="217" covered="0"/>
    <counter type="COMPLEXITY" missed="61" covered="0"/>
    <counter type="METHOD" missed="44" covered="0"/>
    <counter type="CLASS" missed="11" covered="0"/>
  </package>
  <counter type="INSTRUCTION" missed="618" covered="0"/>
  <counter type="BRANCH" missed="34" covered="0"/>
  <counter type="LINE" missed="217" covered="0"/>
  <counter type="COMPLEXITY" missed="61" covered="0"/>
  <counter type="METHOD" missed="44" covered="0"/>
  <counter type="CLASS" missed="11" covered="0"/>
</report>
```

so I think jacoco is at fault.

**Comment by mattnworb** [comment]
same results with jacoco-maven-plugin:0.7.9 too, which is the latest: http://www.jacoco.org/jacoco/trunk/doc/changes.html

**Comment by mattnworb** [comment]
If I run `mvn clean test`, then the HTML report generated by jacoco for hamcrest-future looks like:

![image](https://cloud.githubusercontent.com/assets/113840/24062901/c070be48-0b33-11e7-9802-6565b4489ab6.png)

but if I instead run `mvn clean verify`, then it looks like:

![image](https://cloud.githubusercontent.com/assets/113840/24062973/055b38f8-0b34-11e7-9b2b-745d034042d4.png)

however I also saw `verify` produce an all red report at least once as well, so it might just be a bug in jacoco (and maybe running `verify` instead of `test` is a red herring).

**Comment by mattnworb** [comment]
After some further investigation, seems like when jacoco reports 0% for hamcrest-future, it is because `target/future/jacoco.exec` is a 0 byte file.

Perhaps something in these tests is causing the JVM running the tests to not exit cleanly and the jacoco agent doesn't have a chance to write `target/future/jacoco.exec` before `jacoco-maven-plugin:report` runs?

**Comment by mattnworb** [comment]
https://groups.google.com/forum/#!topic/jacoco/tC4iKbDDf-I

>  At start JaCoCo creates file with a zero size to ensure that location is writable, then it uses "Runtime.addShutdownHook" to write data at the end of JVM execution, but indeed if JVM is not terminated properly, then shutdown hooks are not guaranteed to be executed. However there are other methods of requesting data - see "Can I collect coverage information without stopping the JVM?" in our FAQ ( http://www.eclemma.org/jacoco/trunk/doc/faq.html ).

**Comment by mattnworb** [comment]
I tried to add a shutdown hook of my own to one of the `hamcrest-future` tests that simply outputs a message to stdout, to check the theory that shutdown hooks not being run is what is causing the empty report - and of course now I get non-empty reports 10 out of 10 times 🙃
